# Site wide configuration

title: 九头鸟龙
description: ""
logo: 120x120.jpg # 120x120 px default image used for Twitter summary card
teaser: 400x250.png # 400x250 px default teaser image used in image archive grid
locale: utf-8
#url: 'https://pengjunlong.github.com'

# Jekyll configuration
highlighter: pygments
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: 九头鸟龙
  email: junlong666@gmail.com
  twitter: junlong666
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: 120x120.jpg # 160x160 px image for author byline
  disqus-shortname: 'pengjunlong'


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
